In [1]:
import numpy as np

In [3]:
runs= np.array([[45,50, 30, 60, 25],    
                 [10, 15, 5, 20, 12],   
                 [80, 60, 75, 100, 90],    
                 [25, 30, 20, 35, 40],    
                 [0, 5, 10, 0, 2],    
                 [50, 55, 60, 65, 70],    
                 [35, 40, 45, 50, 55],    
                 [100, 110, 120, 115, 125],   
                 [10, 12, 15, 10, 8],    
                 [70, 80, 85, 90, 95],   
                 [40, 45, 50, 55, 60] ])

In [5]:
runs

array([[ 45,  50,  30,  60,  25],
       [ 10,  15,   5,  20,  12],
       [ 80,  60,  75, 100,  90],
       [ 25,  30,  20,  35,  40],
       [  0,   5,  10,   0,   2],
       [ 50,  55,  60,  65,  70],
       [ 35,  40,  45,  50,  55],
       [100, 110, 120, 115, 125],
       [ 10,  12,  15,  10,   8],
       [ 70,  80,  85,  90,  95],
       [ 40,  45,  50,  55,  60]])

In [15]:
np.sum(runs,axis=1)

array([210,  62, 405, 150,  17, 300, 225, 570,  55, 420, 250])

In [19]:
np.max(runs)

125

In [21]:
average_runs_by_player = np.mean(runs, axis=1)
print("Average runs per match by each player:", average_runs_by_player)

Average runs per match by each player: [ 42.   12.4  81.   30.    3.4  60.   45.  114.   11.   84.   50. ]


In [27]:
sales_data = np.array([[150, 200, 250, 300, 400, 350, 500],  # Product 1    
                        [120, 180, 210, 240, 310, 280, 400],  # Product 2    
                        [100, 130, 190, 220, 300, 270, 350],  # Product 3    
                        [80,  90,  150, 180, 240, 220, 300],  # Product 4    
                        [50,  60,  80,  100, 130, 120, 180]]) # Product 5

In [29]:
sales_data

array([[150, 200, 250, 300, 400, 350, 500],
       [120, 180, 210, 240, 310, 280, 400],
       [100, 130, 190, 220, 300, 270, 350],
       [ 80,  90, 150, 180, 240, 220, 300],
       [ 50,  60,  80, 100, 130, 120, 180]])

In [35]:
sales_data.shape

(5, 7)

In [43]:
sales_data.dtype

dtype('int32')

In [45]:
sales_data.ndim 

2

In [47]:
sales_data.size

35

In [51]:
sales_data.nbytes

140

In [59]:
sales_data[2, 3] # for the Product 3 on Day 4

220

In [63]:
sales_data[0,:]#All sales data for Product 1.

array([150, 200, 250, 300, 400, 350, 500])

In [65]:
sales_data[:, -2:]#Sales data for the last 2 days.


array([[350, 500],
       [280, 400],
       [270, 350],
       [220, 300],
       [120, 180]])